### ISSUE TITLE
The editor won't open.

### ISSUE THREAD

**Issue by RileyDevGithub** [adriengivry/Overload#255] opened 2023-07-15 10:55 UTC
**Description**
The engine immediately closes when opening a project. The project hub opens, though.

**To Reproduce**
1. Go to the location with the '.ovproject' file
2. Click on the file and (if prompted), select the Overload.exe file in your installation to open it with.
3. Editor window pops up and immediately closes.

**Expected behavior**
I suppose the engine is supposed to open and allow easy editing.

**Comment by adriengivry** [comment] 2023-07-15 19:23
Potentially a duplicate of https://github.com/adriengivry/Overload/issues/182

Can you check your driver version?

**Comment by RileyDevGithub** [comment] 2023-07-20 18:21
GPU: Intel(R) UHD Graphics 600
PC: Geobook 140 Minecraft Edition (Green)

**Comment by adriengivry** [comment] 2023-07-20 18:34
@RileyDevGithub yep this GPU doesn't support OpenGL 4.5, which is required to run the 1.3 release build of Overload. You can run Overload by compiling it yourself from the source (see README page). Next release (1.4) will fix that issue.

**Closed by adriengivry** 2023-07-20 18:34 UTC
Labels: Bug

**Comment by RileyDevGithub** [comment] 2023-07-20 18:35
Thanks! Guess I'm out! Bye

**Comment by adriengivry** [comment] 2023-07-20 18:36
@RileyDevGithub Well the issue is fixed on develop, so feel free to try it out!

**Comment by RileyDevGithub** [comment] 2023-08-09 17:50
Bye!

**Comment by RileyDevGithub** [comment] 2023-08-15 17:40
1.3.0 doesn't fix it.
